# Generated by Django 5.2.8 on 2026-03-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_education_end_year_alter_experience_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='possible_next_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
