# Generated by Django 5.2.8 on 2026-03-04 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_possible_next_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap_skill', models.CharField(max_length=255)),
                ('confidence', models.TextField(help_text='Explanation of why this gap exists based on the profile')),
                ('is_manual', models.BooleanField(default=False, help_text='True if the user added/edited this manually. Protects from AI overwrites.')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='user_profile.userprofile')),
            ],
        ),
    ]
