# Generated by Django 5.2.8 on 2026-03-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_skillgap'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgap',
            name='reason',
            field=models.TextField(blank=True, help_text='Short explanation for justification of this gap', null=True),
        ),
        migrations.AlterField(
            model_name='skillgap',
            name='confidence',
            field=models.FloatField(default=0.5, help_text='Confidence level from 0.0 to 1.0'),
        ),
    ]
