# Generated by Django 5.2.8 on 2026-03-05 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_skillgap_reason_alter_skillgap_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chat_message_count',
            field=models.IntegerField(default=0, help_text='Tracks total user messages to trigger background profiler'),
        ),
        migrations.CreateModel(
            name='LearningInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('goal', 'Goal'), ('preference', 'Preference'), ('focus_area', 'Focus Area')], max_length=20)),
                ('content', models.CharField(help_text="Short text describing the user's goal, preference, or focus area", max_length=300)),
                ('is_manual', models.BooleanField(default=False, help_text='True if the user added/edited this manually. Protects from AI overwrites.')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_insights', to='user_profile.userprofile')),
            ],
            options={
                'unique_together': {('profile', 'insight_type', 'content')},
            },
        ),
    ]
