# Generated by Django 5.2.8 on 2026-03-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_userprofile_chat_message_count_learninginsight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='full_name',
        ),
    ]
