# Generated by Django 5.2.8 on 2026-03-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_rename_name_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninginsight',
            name='reason',
            field=models.CharField(blank=True, help_text="AI justification for this insight based on the user's chat history.", max_length=500, null=True),
        ),
    ]
