# Generated by Django 5.2.8 on 2026-02-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersona',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
