# Generated by Django 5.2.8 on 2026-02-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_userpersona_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersona',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
