# Generated by Django 5.2.8 on 2026-01-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_objectives',
        ),
        migrations.AddField(
            model_name='book',
            name='book_summary',
            field=models.TextField(blank=True),
        ),
    ]
