# Generated by Django 5.2.8 on 2026-01-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_alter_article_author_alter_article_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='embed_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
