# Generated by Django 5.2.8 on 2026-03-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_alter_article_thumbnail_alter_article_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_saved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_saved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_saved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='is_saved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
