# Generated by Django 5.2.8 on 2026-01-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='New chat', max_length=255),
        ),
    ]
