# Generated by Django 5.2.8 on 2026-02-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='file_search_store_name',
            field=models.CharField(blank=True, help_text='Google Gemini File Search Store ID for this session', max_length=255, null=True),
        ),
    ]
